@extends('backend.layouts.docadhesion')
@include('backend.includes.adhesion_pagina_1')
@include('backend.includes.adhesion_pagina_2')
@include('backend.includes.adhesion_pagina_3')
@include('backend.includes.adhesion_pagina_4')